
Spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/alfadairy
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  profiles:
    active: local

logging:
  level:
    org.hibernate.SQL: debug
